# Site
name: 'Havva Nur Elveren'
description: 'Havva Nur Elverens personal blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'havvanurelveren'
email: 'havvanuraydin@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    havva:
      name:           Havva Nur
      site:           https://www.havvanurelveren.com
      avatar:         
      bio:            "Hi, I am Havva, the author of this blog!"
      email:          
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: havva
      avatar: 
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
